### PR TITLE
fix: override autoprefixer to remove color adjust warning

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

### CODE REVIEW

**Comment by ankitm123** [comment]
Fixes the annoying warning message:
```
[vite:css] Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated
```

**Comment by ankitm123** [comment]
Need to do the following steps:
* remove node_modules and package-lock.json
* `npm i --save-exact`

**Review by rajatgupta24 — APPROVED** [review]
lgtm

**Pull request merged**
